---
# 1. Installer les pré-requis pour que apt puisse utiliser des dépôts en HTTPS
- name: Installer les dépendances pour Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-docker # Nécessaire pour qu'Ansible pilote Docker
    state: present
    update_cache: yes

# 2. Ajouter la clé GPG officielle de Docker
- name: Ajouter la clé GPG officielle de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# 3. Ajouter le dépôt (repository) officiel Docker
- name: Ajouter le dépôt Docker stable
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

# 4. Installation complète (Moteur + CLI + Plugin Compose V2)
# C'est ici qu'on a ajouté "docker-compose-plugin" pour corriger ton erreur
- name: Installer Docker CE et le plugin Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

# 5. Démarrer le service
- name: Démarrer et activer le service Docker
  service:
    name: docker
    state: started
    enabled: yes

# 6. Gestion des droits utilisateur
- name: Ajouter l'utilisateur ubuntu au groupe docker
  user:
    name: ubuntu
    groups: docker
    append: yes