---
- name: Créer le dossier pour l'application Inception
  file:
    path: /home/ubuntu/inception
    state: directory
    mode: '0755'

- name: Copier le fichier docker-compose.yml (avec injection des variables)
  template:
    src: docker-compose.yml.j2
    dest: /home/ubuntu/inception/docker-compose.yml
    mode: '0644'

- name: Arrêter les anciens conteneurs (au cas où)
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/inception
    state: absent
  ignore_errors: yes

- name: Lancer la stack Inception (WordPress + MariaDB + PhpMyAdmin)
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/inception
    state: present
    build: always
    pull: always